# Welcome to Jekyll!
#
# 关于主题
#
# 优雅作家的另一个主题，具有现代扁平风格和美丽的夜间/黑暗模式.
#
# 网站: https://github.com/jeffreytse/jekyll-theme-yat
#
# 你可以做任何你想做的事情，包括为你的客户做的项目，只要你提到一个归属（在页脚或项目中创建链接）
# 查看许可证文件.
#
# 此配置文件适用于影响整个博客的设置，您应该设置一次并且之后很少编辑的值。.
#
# 出于技术原因，当您使用“bundle exec jekyll serve”时，*不会*自动重新加载此文件。
# 如果您更改此文件，请重新启动服务器进程。.
#
# 网站设置
# 这些用于个性化您的新网站. 如果您查看 HTML 文件,
# 您将看到它们通过 {{ site.title }}, {{ site.email }} 等方式访问.
# 您可以创建任何您想要的自定义变量，并且可以通过 {{ site.myvariable }} 在模板中访问它们。
# theme: owner/name --> Don't forget to remove/comment the gem-based theme option
theme: jekyll-theme-yat
remote_theme: "jeffreytse/jekyll-theme-yat"
#
title: waitusz 博客
email: solon.sz@gmail.com
author: waitusz
copyright: Copyright © 2022
description: >- # 这意味着在“baseurl:”之前忽略换行符
  在这里为您的新网站写一个很棒的描述。您可以在 _config.yml 中编辑此行。它将出现在您的文档头部元数据（用于 Google 搜索结果）和您的 feed.xml 站点描述中.

baseurl: "" # 您网站的子路径，例如 /blog
url: "" # 您网站的基本主机名和协议，例如 http://example.com
favicon: "" # 您网站的图标

# Yat 日期格式
# 如果你想自定义，请参考 https://shopify.github.io/liquid/filters/date/
yat:
  date_format: "%b %d, %Y"

# 如果你想要更多的调试日志，你可以设置 true
# debug: false

# 如果你不想要透明标题，你可以设置 false
# header_transparent: true

# Google 分析
# google_analytics: [Tracking ID]

# 如果要生成网站站点地图，可以设置 true
# sitemap: false

# 如果要更改站点语言，可以设置 lang 选项
 lang: "zh-CN"  # 默认语言是 cn

# Translate languges
# langs refer to https://cloud.google.com/translate/docs/languages
# translate_langs:
#   - lang: en
#     img: https://cdn.countryflags.com/thumbs/united-states-of-america/flag-400.png
#     text: English
#
#   - lang: fr
#     img: https://cdn.countryflags.com/thumbs/france/flag-400.png
#     text: French
#
#   - lang: zh-CN
#     img: https://cdn.countryflags.com/thumbs/china/flag-400.png
#     text: Chinese(Simple)
#
#   - lang: ja
#     img: https://cdn.countryflags.com/thumbs/japan/flag-400.png
#     text: Japanese
#
#   - lang: ko
#     img: https://cdn.countryflags.com/thumbs/south-korea/flag-400.png
#     text: Korean
#
#   - lang: ru
#     img: https://cdn.countryflags.com/thumbs/russia/flag-400.png
#     text: Russian

# 您可以选择主题颜色
# 默认主题颜色如下:
# coolblack: #090a0b
# spacegrey: #353535
# snowwhite: #ffffff
#
# theme_color: snowwhite
#
# Custom color as below:
# theme_color: "#882250"

# You can choose a brand color
# Default brand colors as below:
# orangered: #ff5100
# greatgold: #f2cb05
# greenblue: #389092
#
# brand_color: orangered
#
# Custom color as below:
# brand_color: "#1a8e42"

# Night/Dark mode
# Default mode is "auto", "auto" is for auto nightshift
# (19:00 - 07:00), "manual" is for manual toggle, and
# "on/off" is for default on/off.
#
# Whatever the user's choice is, it will supersede the
# default setting of the site and be kept during the
# visit (session). Only the dark mode setting is"manual",
# it will be always kept on every visit (i.e. no matter
# the browser is closed or not)
#
# night_mode: "auto"

# 代码标记设置
# 您可以启用或禁用代码标记等
 code_badge:
   enabled: "true"
   color: "#fff"
   background_color: "#ff4e00"
   text_transform: "uppercase"  # ("uppercase", "lowercase", "capitalize")

# 如果您只想链接标题中的特定页面，请取消注释
# 这并按顺序添加页面的路径，因为它们应该显示
# header_pages:
#   - index.html
#   - archives.html
#   - categories.html
#   - tags.html
#   - about.md

# 页面默认值
# defaults:
#   home:
#     heading: "你很棒的标题"
#     subheading: "你很棒的副标题"
#     banner: "你的图片网址"

# Banner 默认设置
# 这些横幅设置用于全局横幅默认设置，但您也可以通过前面的内容为特定帖子配置它
# banner:
#   video: null             # Video banner source
#   loop: true              # Video loop
#   volume: 0               # Video volume (100% is 1.0)
#   start_at: 0             # Video start time
#   image: null             # 图片banner来源
#   opacity: 1.0            # Banner 不透明度 (100% is 1.0)
#   background: "rgba(0, 0, 0, 0.8)"  # Banner 背景（可能是图像）
#   height: "640px"         # Banner 默认高度
#   min_height: null        # Banner 最小高度
#   heading_style: null     # 自定义标题样式 (e.g. "font-weight: bold; text-decoration: underline")
#   subheading_style: null  # 自定义副标题样式 (e.g. color: gold)

# Excerpt size setting 摘录大小设置
# excerpt_size: 350

# Pagination setting 分页设置
# paginate: 5

# Disqus 评论
# disqus:
#   shortname: "您的 Disqus 用户名"

# Gitment 评论
# gitment:
#   username: "您的 GitHub 用户名"
#   repo: "存储评论的仓库"
#   client_id: "您的客户 ID"
#   client_secret: "您的客户秘密"
#   redirect_uri: "您的重定向网址"   # 如果您使用自定义域名

# 构建设置
# highlighter: none
markdown: kramdown
kmarkdown:
  input: GFM

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-spaceship
